<?php
/* Implement hook_block_info */
function featured_carousel_block_info() {
	$blocks['featured_carousel'] = array(
		'info' => t('Featured Carousel'),
		'cache' => DRUPAL_NO_CACHE,
	);

  return $blocks;
}

/* Implement hook_block_view */
function featured_carousel_block_view($delta = '') {
  $block = array();
  $block['content'] = '';
  switch ($delta) {
    case 'featured_carousel':
    /*
      $images = array();
      $libraries = libraries_get_libraries();
      if(isset($libraries['flexslider'])) {
        drupal_add_js($libraries['flexslider'] . '/jquery.flexslider-min.js');
        drupal_add_css($libraries['flexslider'] . '/flexslider.css');
        drupal_add_css(drupal_get_path('module','featured_carousel') . '/featured_carousel.css', array('group' => CSS_THEME));
        $images = file_scan_directory(file_build_uri('carousel'), '/.*\.jpg$/');
      }      
      $block['content'] = theme('featured_carousel', array('images'=>$images));
    */      
      drupal_add_css(drupal_get_path('module','featured_carousel') . '/featured_carousel.css', array('group' => CSS_THEME));
      $images = file_scan_directory(file_build_uri('carousel'), '/.*\.(?:jpg|jpeg|gif|png)$/i');      
      if(!empty($images)) {
        $image_id = rand(1,count($images))-1;
        $count = 0;
        foreach($images as $image) {
          if($count == $image_id): $block['content'] = theme('featured_carousel', array('image'=>$image)); break; endif;
          $count++;
        }        
      }      
      break;    
  }

  return $block;
}

/* Implement hook_theme */
function featured_carousel_theme() {
  return array(
    'featured_carousel' => array(
      'varialbes' => array(
        'image' => array(),
      ),
      'template' => 'featured_carousel',
    ),
  );
}